repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-case-conflict
      - id: check-added-large-files
      - id: check-symlinks
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-yaml
        args: [--unsafe]
      - id: check-toml
      ## the blow 2 checks on python < 3.12 can not support type statement!
      ## disable it!
      # - id: check-ast
      # - id: check-builtin-literals
      - id: check-docstring-first

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.2
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi, jupyter]
        # args: [ --fix ]
      # Run the formatter.
      # - id: ruff-format
      #   types_or: [ python, pyi, jupyter ]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: "0.28.0"
    hooks:
      - id: check-github-workflows
      - id: check-readthedocs
