# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2

jobs:

  test-cpy27:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: python setup.py test
      - store_test_results:
          path: test-reports

  test-cpy34:
    docker:
      - image: circleci/python:3.4
    steps:
      - checkout
      - run: python3 setup.py test
      - store_test_results:
          path: test-reports

  test-cpy35:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run: python3 setup.py test
      - store_test_results:
          path: test-reports

  test-cpy36:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: python3 setup.py test
      - store_test_results:
          path: test-reports

  deploy:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: pip install --user -r requires/distribute.txt
      - run: python setup.py test
      - store_test_results:
          path: test-reports
      - run: python3 setup.py sdist bdist_wheel
      - run: python3 -m twine upload -u ${PYPI_USER} -p ${PYPI_PASSWORD} dist/*

workflows:
  version: 2
  test-and-deploy: # name of your workflow
    jobs:
      - test-cpy27
      - test-cpy34
      - test-cpy35
      - test-cpy36
      - deploy:
          requires:
            - test-cpy27
            - test-cpy34
            - test-cpy35
            - test-cpy36
          filters:
            tags:
              only: /(v?(?:(?:(?P<epoch>[0-9]+)!)?(?P<release>[0-9]+(?:\.[0-9]+)*)(?P<pre>[-_\.]?(?P<pre_l>(a|b|c|rc|alpha|beta|pre|preview))[-_\.]?(?P<pre_n>[0-9]+)?)?(?P<post>(?:-(?P<post_n1>[0-9]+))|(?:[-_\.]?(?P<post_l>post|rev|r)[-_\.]?(?P<post_n2>[0-9]+)?))?(?P<dev>[-_\.]?(?P<dev_l>dev)[-_\.]?(?P<dev_n>[0-9]+)?)?)(?:\+(?P<local>[a-z0-9]+(?:[-_\.][a-z0-9]+)*))?)/
