# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2

references:
  tests_steps: &tests_steps
    steps:
      - checkout
      - run: export PATH=${PATH}:/home/circleci/.local/bin
      - run: pip install --user --requirement requirements/ci.txt
      - run: coverage run setup.py test
      - store_test_results:
          path: test-reports
      - run: coverage xml
      - run: python-codacy-coverage -r coverage.xml

  deploy_steps: &deploy_steps
    steps:
      - checkout
      - run: export PATH=${PATH}:/home/circleci/.local/bin
      - run: pip install --user --requirement requirements/ci.txt
      - run: python setup.py sdist bdist_wheel
      - run: twine upload -u ${PYPI_USER} -p ${PYPI_PASSWORD} dist/*

jobs:

  test-cpy27:
    docker:
      - image: circleci/python:2.7
    <<: *tests_steps

  test-cpy34:
    docker:
      - image: circleci/python:3.4
    <<: *tests_steps

  test-cpy35:
    docker:
      - image: circleci/python:3.5
    <<: *tests_steps

  test-cpy36:
    docker:
      - image: circleci/python:3.6
    <<: *tests_steps

  deploy:
    docker:
      - image: circleci/python:3
    <<: *deploy_steps

workflows:
  version: 2
  test-and-deploy: # name of your workflow
    jobs:
      - test-cpy27
      - test-cpy34
      - test-cpy35
      - test-cpy36
      - deploy:
          requires:
            - test-cpy27
            - test-cpy34
            - test-cpy35
            - test-cpy36
          filters:
            branches:
              only: master
